# Parsed and Annotated Data
## Completed by William Brannock (svv8fs)

Here we create the LIB, CORPUS, and VOCAB tables for the Parsed and Annotated Data section of the Final Project.

The class notebook here was what I used as the major guide for this part: https://www.kaggle.com/code/ontoligent/uva-ds-5001-m04-01-pipeline

# Imports

In [1]:
from glob import glob
from pathlib import Path
import re

import nltk
import numpy as np
import pandas as pd
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.tokenize import RegexpTokenizer

In [2]:
nltk.download("punkt", quiet=True)
nltk.download("punkt_tab", quiet=True)
nltk.download("averaged_perceptron_tagger_eng", quiet=True)
nltk.download("stopwords", quiet=True)

True

## Config

In [3]:
data_home = "."
output_dir = "output"
source_file_dir = f"{data_home}/data"
data_prefix = "constitutions"
CSV_DELIM = "|"

In [4]:
# OHCO setup
OHCO = [
    "constitution_id",
    "provision_num",
    "para_num",
    "sent_num",
    "token_num",
]

clip_pats = [
    r"^Share$"
]

# Go through source .txt files

In [5]:
source_file_list = sorted(glob(f"{source_file_dir}/*.txt"))
source_file_list[:10], len(source_file_list)

(['./data/Afghanistan_2004.txt',
  './data/Albania_2008.txt',
  './data/Algeria_2008.txt',
  './data/Andorra_1993.txt',
  './data/Angola_2010.txt',
  './data/Antigua_and_Barbuda_1981.txt',
  './data/Argentina_1994.txt',
  './data/Armenia_2005.txt',
  './data/Australia_1985.txt',
  './data/Austria_2009.txt'],
 192)

In [ ]:
# Parsing helper functions
def parse_filename(source_file_path):
    stem = Path(source_file_path).stem
    country, file_year = stem.rsplit("_", 1)
    return stem, country.replace("_", " "), int(file_year)


# Get out title, original year, and revision year from the first line of the file
def parse_title_line(line):
    title_pat = re.compile(r"^(?P<title>.*?)(?:\s+(?P<original_year>\d{4}))?(?:\s+\(rev\.\s*(?P<revision_year>\d{4})\))?\s*$")
    match = title_pat.match(line.strip())
    if not match:
        return line.strip(), pd.NA, pd.NA
    original_year = match.group("original_year")
    revision_year = match.group("revision_year")
    return (
        match.group("title").strip(),
        int(original_year) if original_year else pd.NA,
        int(revision_year) if revision_year else pd.NA,
    )


# Parse book metadata
book_data = []
for source_file_path in source_file_list:
    constitution_id, country, file_year = parse_filename(source_file_path)
    raw_title = Path(source_file_path).read_text(encoding="utf-8", errors="ignore").splitlines()[0]
    book_data.append((constitution_id, source_file_path, raw_title, country, file_year))

book_data[:5]

[('Afghanistan_2004',
  './data/Afghanistan_2004.txt',
  'Afghanistan 2004',
  'Afghanistan',
  2004),
 ('Albania_2008',
  './data/Albania_2008.txt',
  'Albania 1998 (rev. 2008)',
  'Albania',
  2008),
 ('Algeria_2008',
  './data/Algeria_2008.txt',
  'Algeria 1963 (rev. 2008)',
  'Algeria',
  2008),
 ('Andorra_1993', './data/Andorra_1993.txt', 'Andorra 1993', 'Andorra', 1993),
 ('Angola_2010', './data/Angola_2010.txt', 'Angola 2010', 'Angola', 2010)]

In [7]:
LIB = pd.DataFrame(
    book_data,
    columns=["constitution_id", "source_file_path", "raw_title", "country", "file_year"]
).set_index("constitution_id").sort_index()
LIB.head()

,source_file_path,raw_title,country,file_year
constitution_id,,,,
Afghanistan_2004,./data/Afghanistan_2004.txt,Afghanistan 2004,Afghanistan,2004
Albania_2008,./data/Albania_2008.txt,Albania 1998 (rev. 2008),Albania,2008
Algeria_2008,./data/Algeria_2008.txt,Algeria 1963 (rev. 2008),Algeria,2008
Andorra_1993,./data/Andorra_1993.txt,Andorra 1993,Andorra,1993
Angola_2010,./data/Angola_2010.txt,Angola 2010,Angola,2010

In [8]:
title_data = LIB.raw_title.apply(parse_title_line).apply(pd.Series)
title_data.columns = ["title", "original_year", "revision_year"]
LIB = LIB.join(title_data).drop("raw_title", axis=1)
LIB.head()

,source_file_path,country,file_year,title,original_year,revision_year
constitution_id,,,,,,
Afghanistan_2004,./data/Afghanistan_2004.txt,Afghanistan,2004,Afghanistan,2004.0,<NA>
Albania_2008,./data/Albania_2008.txt,Albania,2008,Albania,1998.0,2008
Algeria_2008,./data/Algeria_2008.txt,Algeria,2008,Algeria,1963.0,2008
Andorra_1993,./data/Andorra_1993.txt,Andorra,1993,Andorra,1993.0,<NA>
Angola_2010,./data/Angola_2010.txt,Angola,2010,Angola,2010.0,<NA>

# Parse Provisions

A provision here is any native structure such as parts, chapters, titles, articles, sections, explanations, clausees, etc.

In [9]:
roman = "[IVXLCDM]+"

provision_pat_list = [
    r"^Preamble$",
    r"^(?:PART|Part)\b",
    r"^(?:TITLE|Title)\b",
    r"^(?:CHAPTER|Chapter)\b",
    r"^(?:SCHEDULE|Schedule)\b",
    rf"^(?:ARTICLE|Article)\s+(?:\d+[A-Z]?|{roman})\b",
    r"^(?:SECTION|Section)\s+[A-Za-z0-9]+\b",
    r"^\d+[A-Z]?\.\s+\S+",
    r"^(?:Explanation|Transitional Provision|Final Provision|Additional Provision)\b",
]
provision_regex = "(?:" + ")|(?:".join(provision_pat_list) + ")"

# save the provision regex in the LIB 
LIB["provision_regex"] = provision_regex

# sentence splitting and tokenization setup
SENT_SPLIT_RE = re.compile(r"(?<=[.!?;:])\s+(?=[A-Z0-9\"'])")
TOKENIZER = RegexpTokenizer(r"[A-Za-z]+(?:'[A-Za-z]+)?|[0-9]+(?:\.[0-9]+)?")


def is_blank_or_clipped(line):
    stripped = line.strip()
    return stripped == "" or any(re.search(pat, stripped) for pat in clip_pats)


def is_provision_boundary(line, provision_regex):
    return re.search(provision_regex, line.strip(), flags=re.IGNORECASE) is not None


def split_sentences(para_str):
    sentences = [s.strip() for s in SENT_SPLIT_RE.split(para_str.strip())]
    return [s for s in sentences if s]


def clean_term(token):
    term = re.sub(r"[\W_]+", "", token).lower()
    return term or pd.NA

In [10]:
def parse_provisions(source_file_path, provision_regex):
    raw_lines = Path(source_file_path).read_text(encoding="utf-8", errors="ignore").splitlines()
    constitution_id, _country, _file_year = parse_filename(source_file_path)

    provisions = []
    current = None
    provision_num = 0

    def close_current():
        nonlocal current
        if current is not None:
            current["provision_str"] = "\n".join(current.pop("lines")).strip()
            if current["provision_str"]:
                provisions.append(current)
            current = None

    def open_provision():
        nonlocal current, provision_num
        close_current()
        provision_num += 1
        current = {
            "constitution_id": constitution_id,
            "provision_num": provision_num,
            "lines": [],
        }

    for raw_line in raw_lines[1:]:
        line = raw_line.strip()

        if is_blank_or_clipped(line):
            if current is not None:
                current["lines"].append("")
            continue

        if is_provision_boundary(line, provision_regex):
            open_provision()

        elif current is None:
            open_provision()

        current["lines"].append(raw_line.rstrip())

    close_current()
    return pd.DataFrame(provisions)

In [11]:
parse_provisions(
    LIB.loc["United_States_of_America_1992"].source_file_path,
    LIB.loc["United_States_of_America_1992"].provision_regex,
).head(20)

,constitution_id,provision_num,provision_str
0,United_States_of_America_1992,1,Preamble\n\n\nWe the People of the United Stat...
1,United_States_of_America_1992,2,Article I
2,United_States_of_America_1992,3,Section 1\n\n\nAll legislative Powers herein g...
3,United_States_of_America_1992,4,Section 2\n\n\nThe House of Representatives sh...
4,United_States_of_America_1992,5,Section 3\n\n\nThe Senate of the United States...
5,United_States_of_America_1992,6,"Section 4\n\n\nThe Times, Places and Manner of..."
6,United_States_of_America_1992,7,Section 5\n\n\nEach House shall be the Judge o...
7,United_States_of_America_1992,8,Section 6\n\n\nThe Senators and Representative...
8,United_States_of_America_1992,9,Section 7\n\n\nAll Bills for raising Revenue s...
9,United_States_of_America_1992,10,Section 8\n\n\nThe Congress shall have Power T...
10,United_States_of_America_1992,11,Section 9\n\n\nThe Migration or Importation of...
11,United_States_of_America_1992,12,Section 10\n\n\nNo State shall enter into any ...
12,United_States_of_America_1992,13,Article II
13,United_States_of_America_1992,14,Section 1\n\n\nThe executive Power shall be ve...
14,United_States_of_America_1992,15,Section 2\n\n\nThe President shall be Commande...
15,United_States_of_America_1992,16,Section 3\n\n\nHe shall from time to time give...
16,United_States_of_America_1992,17,"Section 4\n\n\nThe President, Vice President a..."
17,United_States_of_America_1992,18,Article III
18,United_States_of_America_1992,19,Section 1\n\n\nThe judicial Power of the Unite...
19,United_States_of_America_1992,20,Section 2\n\n\nThe judicial Power shall extend...

# Tokenizing The Corpus

In [12]:
def tokenize_constitution(source_file_path, provision_regex):
    PROVISIONS = parse_provisions(source_file_path, provision_regex)
    tokens = []

    for provision in PROVISIONS.to_dict("records"):
        base = {
            "constitution_id": provision["constitution_id"],
            "provision_num": provision["provision_num"],
        }
        paras = [p.strip() for p in re.split(r"\n\s*\n+", provision["provision_str"]) if p.strip()]

        for para_num, para_str in enumerate(paras, start=1):
            sentence_tokens = []
            for sent_str in split_sentences(para_str):
                sent_tokens = TOKENIZER.tokenize(sent_str)
                if sent_tokens:
                    sentence_tokens.append(sent_tokens)

            if not sentence_tokens:
                continue

            tagged_sentences = nltk.pos_tag_sents(sentence_tokens, lang="eng")
            for sent_num, tagged_sentence in enumerate(tagged_sentences, start=1):
                for token_num, (token_str, pos) in enumerate(tagged_sentence, start=1):
                    tokens.append({
                        **base,
                        "para_num": para_num,
                        "sent_num": sent_num,
                        "token_num": token_num,
                        "token_str": token_str,
                        "term_str": clean_term(token_str),
                        "pos": pos,
                    })

    TOKENS = pd.DataFrame(tokens)
    TOKENS = TOKENS.dropna(subset=["term_str"])
    TOKENS = TOKENS.set_index(OHCO).sort_index()
    return TOKENS, PROVISIONS


def tokenize_collection(LIB):
    corpora = []
    provision_tables = []

    for constitution_id in LIB.index:
        print("Tokenizing", constitution_id, LIB.loc[constitution_id].title)
        source_file_path = LIB.loc[constitution_id].source_file_path
        provision_regex = LIB.loc[constitution_id].provision_regex
        TOKENS, PROVISIONS = tokenize_constitution(source_file_path, provision_regex)
        corpora.append(TOKENS)
        provision_tables.append(PROVISIONS)

    CORPUS = pd.concat(corpora).sort_index()
    PROVISIONS = pd.concat(provision_tables, ignore_index=True)
    print("Done")
    return CORPUS, PROVISIONS

In [13]:
CORPUS, PROVISIONS = tokenize_collection(LIB)
CORPUS.head()

Tokenizing Afghanistan_2004 Afghanistan
Tokenizing Albania_2008 Albania
Tokenizing Algeria_2008 Algeria
Tokenizing Andorra_1993 Andorra
Tokenizing Angola_2010 Angola
Tokenizing Antigua_and_Barbuda_1981 Antigua and Barbuda
Tokenizing Argentina_1994 Argentina 1853 (reinst. 1983, rev. 1994)
Tokenizing Armenia_2005 Armenia
Tokenizing Australia_1985 Australia
Tokenizing Austria_2009 Austria 1920 (reinst. 1945, rev. 2009)
Tokenizing Azerbaijan_2009 Azerbaijan
Tokenizing Bahamas_2002 Bahamas
Tokenizing Bahrain_2002 Bahrain
Tokenizing Bangladesh_2011 Bangladesh 1972 (reinst. 1986, rev. 2011)
Tokenizing Barbados_2007 Barbados
Tokenizing Belarus_2004 Belarus
Tokenizing Belgium_2012 Belgium
Tokenizing Belize_2001 Belize
Tokenizing Benin_1990 Benin
Tokenizing Bhutan_2008 Bhutan
Tokenizing Bolivia_2009 Bolivia
Tokenizing Bosnia_Herzegovina_2009 Bosnia-Herzegovina
Tokenizing Botswana_2002 Botswana
Tokenizing Brazil_2014 Brazil
Tokenizing Brunei_1984 Brunei
Tokenizing Bulgaria_2007 Bulgaria
Tokenizing Burkina_Faso_2012 Burkina Faso
Tokenizing Burundi_2005 Burundi
Tokenizing Cambodia_1999 Cambodia
Tokenizing Cameroon_2008 Cameroon
Tokenizing Canada_2011 Canada
Tokenizing Cape_Verde_1992 Cape Verde
Tokenizing Central_African_Republic_2010 Central African Republic
Tokenizing Chad_2005 Chad
Tokenizing Chile_2012 Chile
Tokenizing China_2004 China
Tokenizing Colombia_2005 Colombia
Tokenizing Comoros_2009 Comoros
Tokenizing Congo_2001 Congo
Tokenizing Costa_Rica_2011 Costa Rica
Tokenizing Cote_DIvoire_2009 Cote D'Ivoire
Tokenizing Croatia_2001 Croatia
Tokenizing Cuba_2002 Cuba
Tokenizing Cyprus_2013 Cyprus
Tokenizing Czech_Republic_2002 Czech Republic
Tokenizing Democratic_Republic_of_the_Congo_2011 Democratic Republic of the Congo
Tokenizing Denmark_1953 Denmark
Tokenizing Djibouti_2010 Djibouti
Tokenizing Dominica_1984 Dominica
Tokenizing Dominican_Republic_2010 Dominican Republic
Tokenizing East_Timor_2002 East Timor
Tokenizing Ecuador_2008 Ecuador
Tokenizing Egypt_2014 Egypt
Tokenizing El_Salvador_2003 El Salvador
Tokenizing Equatorial_Guinea_1995 Equatorial Guinea
Tokenizing Eritrea_1997 Eritrea
Tokenizing Estonia_2003 Estonia
Tokenizing Ethiopia_1994 Ethiopia
Tokenizing Fiji_2013 Fiji
Tokenizing Finland_2011 Finland
Tokenizing France_2008 France
Tokenizing Gabon_1997 Gabon
Tokenizing Gambia_2004 Gambia
Tokenizing Georgia_2004 Georgia
Tokenizing German_Federal_Republic_2012 German Federal Republic
Tokenizing Ghana_1996 Ghana
Tokenizing Greece_2008 Greece
Tokenizing Grenada_1992 Grenada 1973 (reinst. 1991, rev. 1992)
Tokenizing Guatemala_1993 Guatemala
Tokenizing Guinea_2010 Guinea
Tokenizing Guinea_Bissau_1991 Guinea-Bissau
Tokenizing Guyana_1995 Guyana
Tokenizing Haiti_2012 Haiti
Tokenizing Honduras_2012 Honduras
Tokenizing Hungary_2011 Hungary
Tokenizing Iceland_1999 Iceland
Tokenizing India_2012 India
Tokenizing Indonesia_2002 Indonesia 1945 (reinst. 1959, rev. 2002)
Tokenizing Iran_1989 Iran
Tokenizing Iraq_2005 Iraq
Tokenizing Ireland_2012 Ireland
Tokenizing Israel_2013 Israel
Tokenizing Italy_2012 Italy
Tokenizing Jamaica_1994 Jamaica
Tokenizing Japan_1946 Japan
Tokenizing Jordan_2011 Jordan
Tokenizing Kazakhstan_1998 Kazakhstan
Tokenizing Kenya_2010 Kenya
Tokenizing Kiribati_1995 Kiribati
Tokenizing Kosovo_2008 Kosovo
Tokenizing Kuwait_1992 Kuwait 1962 (reinst. 1992)
Tokenizing Kyrgyz_Republic_2010 Kyrgyz Republic
Tokenizing Laos_2003 Laos
Tokenizing Latvia_2007 Latvia 1922 (reinst. 1991, rev. 2007)
Tokenizing Lebanon_2004 Lebanon
Tokenizing Lesotho_1998 Lesotho
Tokenizing Liberia_1986 Liberia
Tokenizing Libya_2011 Libya
Tokenizing Liechtenstein_2003 Liechtenstein
Tokenizing Lithuania_2006 Lithuania
Tokenizing Luxembourg_2009 Luxembourg
Tokenizing Macedonia_2011 Macedonia
Tokenizing Madagascar_2010 Madagascar
Tokenizing Malawi_1999 Malawi
Tokenizing Malaysia_1996 Malaysia
Tokenizing Maldives_2008 Maldives
Tokenizing Mali_1992 Mali
Tokenizing Malta_2011 Malta
Tokenizing Marshall_Islands_1995 Marshall Islands
Tokenizing Mauritania_2012 Mauritania
Tokenizing Mauritius_2011 Mauritius
Tokenizing Mexico_2007 Mexico
Tokenizing Micronesia_1990 Micronesia
Tokenizing Moldova_2006 Moldova
Tokenizing Monaco_2002 Monaco
Tokenizing Mongolia_2001 Mongolia
Tokenizing Montenegro_2007 Montenegro
Tokenizing Morocco_2011 Morocco
Tokenizing Mozambique_2007 Mozambique
Tokenizing Myanmar_2008 Myanmar
Tokenizing Namibia_2010 Namibia
Tokenizing Nauru_1968 Nauru
Tokenizing Nepal_2010 Nepal
Tokenizing Netherlands_2008 Netherlands
Tokenizing Nicaragua_2005 Nicaragua
Tokenizing Niger_2010 Niger
Tokenizing Nigeria_1999 Nigeria
Tokenizing Norway_2004 Norway
Tokenizing Oman_2011 Oman
Tokenizing Pakistan_2012 Pakistan 1973 (reinst. 2002, rev. 2012)
Tokenizing Palau_1992 Palau
Tokenizing Panama_2004 Panama
Tokenizing Papua_New_Guinea_1991 Papua New Guinea
Tokenizing Paraguay_2011 Paraguay
Tokenizing Peoples_Republic_of_Korea_1998 People's Republic of Korea
Tokenizing Peru_2009 Peru
Tokenizing Philippines_1987 Philippines
Tokenizing Poland_1997 Poland
Tokenizing Portugal_2005 Portugal
Tokenizing Qatar_2003 Qatar
Tokenizing Republic_of_Korea_1987 Republic of Korea
Tokenizing Romania_2003 Romania
Tokenizing Russia_2008 Russia
Tokenizing Rwanda_2010 Rwanda
Tokenizing Samoa_2010 Samoa
Tokenizing Sao_Tome_and_Principe_1990 Sao Tome and Principe
Tokenizing Saudi_Arabia_2005 Saudi Arabia
Tokenizing Senegal_2009 Senegal
Tokenizing Serbia_2006 Serbia
Tokenizing Seychelles_2011 Seychelles
Tokenizing Sierra_Leone_2008 Sierra Leone 1991 (reinst. 1996, rev. 2008)
Tokenizing Singapore_2010 Singapore
Tokenizing Slovakia_2001 Slovakia
Tokenizing Slovenia_2006 Slovenia
Tokenizing Socialist_Republic_of_Vietnam_2001 Socialist Republic of Vietnam
Tokenizing Solomon_Islands_2009 Solomon Islands
Tokenizing Somalia_2012 Somalia
Tokenizing South_Africa_2012 South Africa
Tokenizing South_Sudan_2011 South Sudan
Tokenizing Spain_2011 Spain
Tokenizing Sri_Lanka_2010 Sri Lanka
Tokenizing St_Kitts_and_Nevis_1983 St. Kitts and Nevis
Tokenizing St_Lucia_1978 St. Lucia
Tokenizing St_Vincent_and_the_Grenadines_1979 St. Vincent and the Grenadines
Tokenizing Sudan_2005 Sudan
Tokenizing Surinam_1992 Surinam
Tokenizing Swaziland_2005 Swaziland
Tokenizing Sweden_2012 Sweden
Tokenizing Switzerland_2002 Switzerland
Tokenizing Syria_2012 Syria
Tokenizing Taiwan_2005 Taiwan
Tokenizing Tajikistan_2003 Tajikistan
Tokenizing Tanzania_1995 Tanzania
Tokenizing Thailand_2007 Thailand
Tokenizing Togo_2007 Togo
Tokenizing Tonga_1988 Tonga
Tokenizing Trinidad_and_Tobago_2007 Trinidad and Tobago
Tokenizing Tunisia_2014 Tunisia
Tokenizing Turkey_2002 Turkey
Tokenizing Turkmenistan_2008 Turkmenistan
Tokenizing Tuvalu_1986 Tuvalu
Tokenizing Uganda_2005 Uganda
Tokenizing Ukraine_2004 Ukraine
Tokenizing United_Arab_Emirates_2004 United Arab Emirates
Tokenizing United_States_of_America_1992 United States of America
Tokenizing Uruguay_2004 Uruguay 1966 (reinst. 1985, rev. 2004)
Tokenizing Uzbekistan_1992 Uzbekistan
Tokenizing Vanuatu_1983 Vanuatu
Tokenizing Venezuela_2009 Venezuela
Tokenizing Yemen_2001 Yemen
Tokenizing Zambia_2009 Zambia
Tokenizing Zimbabwe_2013 Zimbabwe
Done

                                                           token_str  \
constitution_id  provision_num para_num sent_num token_num
Afghanistan_2004 1             1        1        1          Preamble
                               2        1        1                In
                                                 2               the
                                                 3              name
                                                 4                of

                                                            term_str pos
constitution_id  provision_num para_num sent_num token_num
Afghanistan_2004 1             1        1        1          preamble  JJ
                               2        1        1                in  IN
                                                 2               the  DT
                                                 3              name  NN
                                                 4                of  IN

In [14]:
CORPUS.query('constitution_id == "United_States_of_America_1992"').tail(20)

                                                                           token_str  \
constitution_id               provision_num para_num sent_num token_num
United_States_of_America_1992 61            2        1        33                  on
                                                              34             account
                                                              35                  of
                                                              36                 age
                              62            1        1        1              Section
                                                              2                    2
                                            2        1        1                  The
                                                              2             Congress
                                                              3                shall
                                                              4                 have
                                                              5                power
                                                              6                   to
                                                              7              enforce
                                                              8                 this
                                                              9              article
                                                              10                  by
                                                              11         appropriate
                                                              12         legislation
                                            3        1        1            Amendment
                                                              2                XXVII

                                                                            term_str  \
constitution_id               provision_num para_num sent_num token_num
United_States_of_America_1992 61            2        1        33                  on
                                                              34             account
                                                              35                  of
                                                              36                 age
                              62            1        1        1              section
                                                              2                    2
                                            2        1        1                  the
                                                              2             congress
                                                              3                shall
                                                              4                 have
                                                              5                power
                                                              6                   to
                                                              7              enforce
                                                              8                 this
                                                              9              article
                                                              10                  by
                                                              11         appropriate
                                                              12         legislation
                                            3        1        1            amendment
                                                              2                xxvii

                                                                         pos
constitution_id               provision_num para_num sent_num token_num
United_States_of_America_1992 61            2        1        33          IN
                                                              34          NN
                                                              35          IN
                                                              36          NN
                              62            1        1        1           NN
                                                              2           CD
                                            2        1        1           DT
                                                              2          NNP
                                                              3           MD
                                                              4           VB
                                                              5           NN
                                                              6           TO
                                                              7           VB
                                                              8           DT
                                                              9           NN
                                                              10          IN
                                                              11          JJ
                                                              12          NN
                                            3        1        1          NNP
                                                              2           NN

# Extract LIB Features

In [15]:
LIB["constitution_len"] = CORPUS.groupby("constitution_id").term_str.count()
LIB["n_provisions"] = PROVISIONS.groupby("constitution_id").provision_num.count()
LIB["n_chars"] = LIB.source_file_path.apply(lambda p: len(Path(p).read_text(encoding="utf-8", errors="ignore")))
LIB.sort_values("constitution_len").head()

,source_file_path,country,file_year,title,original_year,revision_year,provision_regex,constitution_len,n_provisions,n_chars
constitution_id,,,,,,,,,,
Libya_2011,./data/Libya_2011.txt,Libya,2011,Libya,2011.0,<NA>,(?:^Preamble$)|(?:^(?:PART|Part)\b)|(?:^(?:TIT...,2922,6,18926
Iceland_1999,./data/Iceland_1999.txt,Iceland,1999,Iceland,1944.0,1999,(?:^Preamble$)|(?:^(?:PART|Part)\b)|(?:^(?:TIT...,4105,80,25334
Monaco_2002,./data/Monaco_2002.txt,Monaco,2002,Monaco,1962.0,2002,(?:^Preamble$)|(?:^(?:PART|Part)\b)|(?:^(?:TIT...,4425,12,28323
Latvia_2007,./data/Latvia_2007.txt,Latvia,2007,"Latvia 1922 (reinst. 1991, rev. 2007)",NaN,NaN,(?:^Preamble$)|(?:^(?:PART|Part)\b)|(?:^(?:TIT...,4789,125,29797
Japan_1946,./data/Japan_1946.txt,Japan,1946,Japan,1946.0,<NA>,(?:^Preamble$)|(?:^(?:PART|Part)\b)|(?:^(?:TIT...,4989,115,31269

# Extract VOCAB

In [16]:
empty_term_mask = CORPUS.term_str.eq("")
empty_term_mask.sum()

np.int64(0)

In [17]:
CORPUS = CORPUS.loc[~empty_term_mask].copy()

In [18]:
CORPUS["pos_group"] = CORPUS.pos.str[:2]
CORPUS.head()

                                                           token_str  \
constitution_id  provision_num para_num sent_num token_num
Afghanistan_2004 1             1        1        1          Preamble
                               2        1        1                In
                                                 2               the
                                                 3              name
                                                 4                of

                                                            term_str pos  \
constitution_id  provision_num para_num sent_num token_num
Afghanistan_2004 1             1        1        1          preamble  JJ
                               2        1        1                in  IN
                                                 2               the  DT
                                                 3              name  NN
                                                 4                of  IN

                                                           pos_group
constitution_id  provision_num para_num sent_num token_num
Afghanistan_2004 1             1        1        1                JJ
                               2        1        1                IN
                                                 2                DT
                                                 3                NN
                                                 4                IN

In [19]:
VOCAB = CORPUS.term_str.value_counts().to_frame("n").sort_index()
VOCAB.index.name = "term_str"
VOCAB["n_chars"] = VOCAB.index.str.len()
VOCAB["p"] = VOCAB.n / VOCAB.n.sum()
VOCAB["i"] = -np.log2(VOCAB.p)
VOCAB.head()

            n  n_chars             p          i
term_str
0          26        1  6.051719e-06  17.334224
00          9        2  2.094826e-06  18.864738
000       210        3  4.887927e-05  14.320418
00000       2        5  4.655168e-07  21.034663
001         5        3  1.163792e-06  19.712735

# Annotate VOCAB

In [20]:
VOCAB["max_pos"] = CORPUS.value_counts(["term_str", "pos"]).unstack(fill_value=0).idxmax(1)
VOCAB["max_pos_group"] = CORPUS.value_counts(["term_str", "pos_group"]).unstack(fill_value=0).idxmax(1)
VOCAB.head()

            n  n_chars             p          i max_pos max_pos_group
term_str
0          26        1  6.051719e-06  17.334224      CD            CD
00          9        2  2.094826e-06  18.864738      CD            CD
000       210        3  4.887927e-05  14.320418      CD            CD
00000       2        5  4.655168e-07  21.034663      CD            CD
001         5        3  1.163792e-06  19.712735      CD            CD

In [21]:
VOCAB["n_pos_group"] = CORPUS.value_counts(["term_str", "pos_group"]).unstack(fill_value=0).astype("bool").sum(1)
VOCAB["cat_pos_group"] = CORPUS.value_counts(["term_str", "pos_group"]).unstack(fill_value=0).astype("bool").apply(lambda x: " ".join(x.index[x]), 1)
VOCAB["n_pos"] = CORPUS.value_counts(["term_str", "pos"]).unstack(fill_value=0).astype("bool").sum(1)
VOCAB["cat_pos"] = CORPUS.value_counts(["term_str", "pos"]).unstack(fill_value=0).astype("bool").apply(lambda x: " ".join(x.index[x]), 1)
VOCAB.head()

/var/folders/2n/rqnjq39x0bl3l55y0ghnzcz00000gn/T/ipykernel_11486/4022745382.py:1: Pandas4Warning: Starting with pandas version 4.0 all arguments of sum will be keyword-only.
  VOCAB["n_pos_group"] = CORPUS.value_counts(["term_str", "pos_group"]).unstack(fill_value=0).astype("bool").sum(1)
/var/folders/2n/rqnjq39x0bl3l55y0ghnzcz00000gn/T/ipykernel_11486/4022745382.py:3: Pandas4Warning: Starting with pandas version 4.0 all arguments of sum will be keyword-only.
  VOCAB["n_pos"] = CORPUS.value_counts(["term_str", "pos"]).unstack(fill_value=0).astype("bool").sum(1)

,n,n_chars,p,i,max_pos,max_pos_group,n_pos_group,cat_pos_group,n_pos,cat_pos
term_str,,,,,,,,,,
0,26,1,6.051719e-06,17.334224,CD,CD,1,CD,1,CD
00,9,2,2.094826e-06,18.864738,CD,CD,1,CD,1,CD
000,210,3,4.887927e-05,14.320418,CD,CD,1,CD,1,CD
00000,2,5,4.655168e-07,21.034663,CD,CD,1,CD,1,CD
001,5,3,1.163792e-06,19.712735,CD,CD,1,CD,1,CD

In [22]:
sw = pd.Series(1, index=stopwords.words("english"), name="stop")
VOCAB["stop"] = VOCAB.index.map(sw).fillna(0).astype("int")
VOCAB.head()

,n,n_chars,p,i,max_pos,max_pos_group,n_pos_group,cat_pos_group,n_pos,cat_pos,stop
term_str,,,,,,,,,,,
0,26,1,6.051719e-06,17.334224,CD,CD,1,CD,1,CD,0
00,9,2,2.094826e-06,18.864738,CD,CD,1,CD,1,CD,0
000,210,3,4.887927e-05,14.320418,CD,CD,1,CD,1,CD,0
00000,2,5,4.655168e-07,21.034663,CD,CD,1,CD,1,CD,0
001,5,3,1.163792e-06,19.712735,CD,CD,1,CD,1,CD,0

In [23]:
stemmer = PorterStemmer()
VOCAB["porter_stem"] = VOCAB.apply(lambda x: stemmer.stem(x.name), 1)
VOCAB.head()

,n,n_chars,p,i,max_pos,max_pos_group,n_pos_group,cat_pos_group,n_pos,cat_pos,stop,porter_stem
term_str,,,,,,,,,,,,
0,26,1,6.051719e-06,17.334224,CD,CD,1,CD,1,CD,0,0
00,9,2,2.094826e-06,18.864738,CD,CD,1,CD,1,CD,0,00
000,210,3,4.887927e-05,14.320418,CD,CD,1,CD,1,CD,0,000
00000,2,5,4.655168e-07,21.034663,CD,CD,1,CD,1,CD,0,00000
001,5,3,1.163792e-06,19.712735,CD,CD,1,CD,1,CD,0,001

# Add DFIDF

In [24]:
DOC = CORPUS.groupby("constitution_id").term_str.count().to_frame("n_tokens")
DOC["n_types"] = CORPUS.reset_index()[["constitution_id", "term_str"]].drop_duplicates().groupby("constitution_id").term_str.count()
DOC["pkr"] = DOC.n_types / DOC.n_tokens
DOC = DOC.join(LIB[["country", "file_year", "original_year", "revision_year", "title"]])
DOC.sort_values("pkr").head(20)

,n_tokens,n_types,pkr,country,file_year,original_year,revision_year,title
constitution_id,,,,,,,,
India_2012,103941,3919,0.037704,India,2012,1949.0,2012,India
St_Kitts_and_Nevis_1983,46896,2106,0.044908,St Kitts and Nevis,1983,1983.0,<NA>,St. Kitts and Nevis
Malaysia_1996,64746,3123,0.048235,Malaysia,1996,1957.0,1996,Malaysia
St_Lucia_1978,40394,1998,0.049463,St Lucia,1978,1978.0,<NA>,St. Lucia
Sweden_2012,59926,3067,0.051180,Sweden,2012,1974.0,2012,Sweden
Jamaica_1994,38422,1974,0.051377,Jamaica,1994,1962.0,1994,Jamaica
Fiji_2013,47371,2448,0.051677,Fiji,2013,2013.0,<NA>,Fiji
Singapore_2010,44342,2307,0.052027,Singapore,2010,1959.0,2010,Singapore
Lesotho_1998,42911,2267,0.052830,Lesotho,1998,1993.0,1998,Lesotho
Sri_Lanka_2010,59855,3186,0.053229,Sri Lanka,2010,1978.0,2010,Sri Lanka
Bahamas_2002,38956,2093,0.053727,Bahamas,2002,1973.0,2002,Bahamas
Pakistan_2012,58432,3213,0.054987,Pakistan,2012,NaN,NaN,"Pakistan 1973 (reinst. 2002, rev. 2012)"
Dominica_1984,36024,1984,0.055074,Dominica,1984,1978.0,1984,Dominica
Belize_2001,40230,2234,0.055531,Belize,2001,1981.0,2001,Belize
Antigua_and_Barbuda_1981,36749,2070,0.056328,Antigua and Barbuda,1981,1981.0,<NA>,Antigua and Barbuda
Papua_New_Guinea_1991,56109,3175,0.056586,Papua New Guinea,1991,1975.0,1991,Papua New Guinea
St_Vincent_and_the_Grenadines_1979,33305,1900,0.057048,St Vincent and the Grenadines,1979,1979.0,<NA>,St. Vincent and the Grenadines
Grenada_1992,32624,1876,0.057504,Grenada,1992,NaN,NaN,"Grenada 1973 (reinst. 1991, rev. 1992)"
Ghana_1996,54326,3169,0.058333,Ghana,1996,1992.0,1996,Ghana
Mauritius_2011,37535,2199,0.058585,Mauritius,2011,1968.0,2011,Mauritius

In [25]:
N = DOC.shape[0]

DF = CORPUS.reset_index()[["constitution_id", "term_str"]].drop_duplicates().term_str.value_counts().sort_index()
IDF = np.log2(N / DF)

VOCAB["df"] = DF
VOCAB["idf"] = IDF
VOCAB["dfidf"] = VOCAB.df * VOCAB.idf
VOCAB["dp"] = VOCAB.df / N
VOCAB["di"] = np.log2(1 / VOCAB.dp)
VOCAB["dh"] = VOCAB.dp * VOCAB.di

VOCAB.sort_values(["dfidf", "n"], ascending=False).head(20)

,n,n_chars,p,i,max_pos,max_pos_group,n_pos_group,cat_pos_group,n_pos,cat_pos,stop,porter_stem,df,idf,dfidf,dp,di,dh
term_str,,,,,,,,,,,,,,,,,,
assent,623,6,0.000145,12.751575,NN,NN,3,JJ NN VB,5,JJ NN NNP VB VBD,0,assent,71,1.435215,101.900292,0.369792,1.435215,0.530731
labor,500,5,0.000116,13.068879,NN,NN,1,NN,2,NN NNP,0,labor,71,1.435215,101.900292,0.369792,1.435215,0.530731
rural,402,5,0.000094,13.383612,JJ,JJ,3,JJ NN VB,3,JJ NNP VB,0,rural,71,1.435215,101.900292,0.369792,1.435215,0.530731
hand,348,4,0.000081,13.591720,NN,NN,1,NN,2,NN NNP,0,hand,71,1.435215,101.900292,0.369792,1.435215,0.530731
servants,347,8,0.000081,13.595871,NNS,NN,2,NN VB,5,NN NNP NNS VBZ NNPS,0,servant,71,1.435215,101.900292,0.369792,1.435215,0.530731
like,303,4,0.000071,13.791489,JJ,JJ,3,JJ IN VB,3,JJ IN VB,0,like,71,1.435215,101.900292,0.369792,1.435215,0.530731
organized,299,9,0.000070,13.810662,VBN,VB,3,JJ NN VB,4,JJ NNP VBN VBD,0,organ,71,1.435215,101.900292,0.369792,1.435215,0.530731
class,291,5,0.000068,13.849788,NN,NN,1,NN,2,NN NNP,0,class,71,1.435215,101.900292,0.369792,1.435215,0.530731
fees,251,4,0.000058,14.063120,NNS,NN,1,NN,1,NNS,0,fee,71,1.435215,101.900292,0.369792,1.435215,0.530731
magistrate,234,10,0.000054,14.164299,NN,NN,3,JJ NN VB,5,JJ NN NNP VB VBP,0,magistr,71,1.435215,101.900292,0.369792,1.435215,0.530731
delivered,221,9,0.000051,14.246761,VBN,VB,2,JJ VB,3,JJ VBN VBD,0,deliv,71,1.435215,101.900292,0.369792,1.435215,0.530731
occasion,221,8,0.000051,14.246761,NN,NN,1,NN,1,NN,0,occas,71,1.435215,101.900292,0.369792,1.435215,0.530731
reading,220,7,0.000051,14.253304,NN,NN,2,NN VB,3,NN NNP VBG,0,read,71,1.435215,101.900292,0.369792,1.435215,0.530731
construction,207,12,0.000048,14.341176,NN,NN,1,NN,2,NN NNP,0,construct,71,1.435215,101.900292,0.369792,1.435215,0.530731
copy,206,4,0.000048,14.348163,NN,NN,1,NN,2,NN NNP,0,copi,71,1.435215,101.900292,0.369792,1.435215,0.530731
read,202,4,0.000047,14.376452,VBN,VB,3,JJ NN VB,7,JJ NN NNP VB VBP VBN VBD,0,read,71,1.435215,101.900292,0.369792,1.435215,0.530731
integral,180,8,0.000042,14.542810,JJ,JJ,2,JJ NN,2,JJ NNP,0,integr,71,1.435215,101.900292,0.369792,1.435215,0.530731
honor,179,5,0.000042,14.550848,NN,NN,4,JJ NN VB PD,7,JJ NN NNP VB NNS VBP PDT,0,honor,71,1.435215,101.900292,0.369792,1.435215,0.530731
requirement,169,11,0.000039,14.633784,NN,NN,1,NN,1,NN,0,requir,71,1.435215,101.900292,0.369792,1.435215,0.530731
regardless,144,10,0.000034,14.864738,NN,NN,4,JJ NN VB RB,5,JJ NN NNP VB RB,0,regardless,71,1.435215,101.900292,0.369792,1.435215,0.530731

# Check Sample Constitutions

In [26]:
sample_ids = [
    "United_States_of_America_1992",
    "India_2012",
    "France_2008",
    "South_Africa_2012",
]

# Check how provisions are parsed
PROVISIONS.loc[PROVISIONS.constitution_id.isin(sample_ids)].head(40)

,constitution_id,provision_num,provision_str
21042,France_2008,1,Preamble\n\n\nThe French people solemnly procl...
21043,France_2008,2,"ARTICLE 1\n\n\nFrance shall be an indivisible,..."
21044,France_2008,3,Title I. ON SOVEREIGNTY
21045,France_2008,4,ARTICLE 2\n\n\nThe language of the Republic sh...
21046,France_2008,5,ARTICLE 3\n\n\nNational sovereignty shall vest...
21047,France_2008,6,ARTICLE 4\n\n\nPolitical parties and groups sh...
21048,France_2008,7,Title II. THE PRESIDENT OF THE REPUBLIC
21049,France_2008,8,ARTICLE 5\n\n\nThe President of the Republic s...
21050,France_2008,9,ARTICLE 6\n\n\nThe President of the Republic s...
21051,France_2008,10,ARTICLE 7\n\n\nThe President of the Republic s...
21052,France_2008,11,ARTICLE 8\n\n\nThe President of the Republic s...
21053,France_2008,12,ARTICLE 9\n\n\nThe President of the Republic s...
21054,France_2008,13,ARTICLE 10\n\n\nThe President of the Republic ...
21055,France_2008,14,ARTICLE 11\n\n\nThe President of the Republic ...
21056,France_2008,15,ARTICLE 11. *\n\n\nThe President of the Republ...
21057,France_2008,16,ARTICLE 12\n\n\nThe President of the Republic ...
21058,France_2008,17,ARTICLE 13\n\n\nThe President of the Republic ...
21059,France_2008,18,ARTICLE 14\n\n\nThe President of the Republic ...
21060,France_2008,19,ARTICLE 15\n\n\nThe President of the Republic ...
21061,France_2008,20,ARTICLE 16\n\n\nWhere the institutions of the ...
21062,France_2008,21,ARTICLE 17\n\n\nThe President of the Republic ...
21063,France_2008,22,ARTICLE 18\n\n\nThe President of the Republic ...
21064,France_2008,23,ARTICLE 19\n\n\nInstruments of the President o...
21065,France_2008,24,Title III. THE GOVERNMENT
21066,France_2008,25,ARTICLE 20\n\n\nThe Government shall determine...
21067,France_2008,26,ARTICLE 21\n\n\nThe Prime Minister shall direc...
21068,France_2008,27,ARTICLE 22\n\n\nInstruments of the Prime Minis...
21069,France_2008,28,ARTICLE 23\n\n\nMembership of the Government s...
21070,France_2008,29,Title IV. PARLIAMENT
21071,France_2008,30,ARTICLE 24\n\n\nParliament shall pass statutes...
21072,France_2008,31,ARTICLE 25\n\n\nAn Institutional Act shall det...
21073,France_2008,32,ARTICLE 26\n\n\nNo Member of Parliament shall ...
21074,France_2008,33,ARTICLE 27\n\n\nNo Member shall be elected wit...
21075,France_2008,34,ARTICLE 28\n\n\nParliament shall sit as of rig...
21076,France_2008,35,ARTICLE 29\n\n\nParliament shall meet in extra...
21077,France_2008,36,ARTICLE 30\n\n\nExcept where Parliament sits a...
21078,France_2008,37,ARTICLE 31\n\n\nMembers of the Government shal...
21079,France_2008,38,ARTICLE 32\n\n\nThe President of the National ...
21080,France_2008,39,ARTICLE 33\n\n\nThe sittings of the two Houses...
21081,France_2008,40,Title V. ON RELATIONS BETWEEN PARLIAMENT AND T...

In [27]:
# Check Corpus structure
CORPUS.reset_index().query("constitution_id in @sample_ids").head(40)

,constitution_id,provision_num,para_num,sent_num,token_num,token_str,term_str,pos,pos_group
1220329,France_2008,1,1,1,1,Preamble,preamble,JJ,JJ
1220330,France_2008,1,2,1,1,The,the,DT,DT
1220331,France_2008,1,2,1,2,French,french,JJ,JJ
1220332,France_2008,1,2,1,3,people,people,NNS,NN
1220333,France_2008,1,2,1,4,solemnly,solemnly,RB,RB
1220334,France_2008,1,2,1,5,proclaim,proclaim,VBP,VB
1220335,France_2008,1,2,1,6,their,their,PRP$,PR
1220336,France_2008,1,2,1,7,attachment,attachment,NN,NN
1220337,France_2008,1,2,1,8,to,to,TO,TO
1220338,France_2008,1,2,1,9,the,the,DT,DT
1220339,France_2008,1,2,1,10,Rights,rights,NNPS,NN
1220340,France_2008,1,2,1,11,of,of,IN,IN
1220341,France_2008,1,2,1,12,Man,man,NNP,NN
1220342,France_2008,1,2,1,13,and,and,CC,CC
1220343,France_2008,1,2,1,14,the,the,DT,DT
1220344,France_2008,1,2,1,15,principles,principles,NNS,NN
1220345,France_2008,1,2,1,16,of,of,IN,IN
1220346,France_2008,1,2,1,17,national,national,JJ,JJ
1220347,France_2008,1,2,1,18,sovereignty,sovereignty,NN,NN
1220348,France_2008,1,2,1,19,as,as,IN,IN
1220349,France_2008,1,2,1,20,defined,defined,VBN,VB
1220350,France_2008,1,2,1,21,by,by,IN,IN
1220351,France_2008,1,2,1,22,the,the,DT,DT
1220352,France_2008,1,2,1,23,Declaration,declaration,NNP,NN
1220353,France_2008,1,2,1,24,of,of,IN,IN
1220354,France_2008,1,2,1,25,1789,1789,CD,CD
1220355,France_2008,1,2,1,26,confirmed,confirmed,NN,NN
1220356,France_2008,1,2,1,27,and,and,CC,CC
1220357,France_2008,1,2,1,28,complemented,complemented,VBN,VB
1220358,France_2008,1,2,1,29,by,by,IN,IN
1220359,France_2008,1,2,1,30,the,the,DT,DT
1220360,France_2008,1,2,1,31,Preamble,preamble,NNP,NN
1220361,France_2008,1,2,1,32,to,to,TO,TO
1220362,France_2008,1,2,1,33,the,the,DT,DT
1220363,France_2008,1,2,1,34,Constitution,constitution,NNP,NN
1220364,France_2008,1,2,1,35,of,of,IN,IN
1220365,France_2008,1,2,1,36,1946,1946,CD,CD
1220366,France_2008,1,2,1,37,and,and,CC,CC
1220367,France_2008,1,2,1,38,to,to,TO,TO
1220368,France_2008,1,2,1,39,the,the,DT,DT

In [28]:
# Check Vocab Structure
VOCAB.sort_values(["dfidf", "n"], ascending=False).head(20)

,n,n_chars,p,i,max_pos,max_pos_group,n_pos_group,cat_pos_group,n_pos,cat_pos,stop,porter_stem,df,idf,dfidf,dp,di,dh
term_str,,,,,,,,,,,,,,,,,,
assent,623,6,0.000145,12.751575,NN,NN,3,JJ NN VB,5,JJ NN NNP VB VBD,0,assent,71,1.435215,101.900292,0.369792,1.435215,0.530731
labor,500,5,0.000116,13.068879,NN,NN,1,NN,2,NN NNP,0,labor,71,1.435215,101.900292,0.369792,1.435215,0.530731
rural,402,5,0.000094,13.383612,JJ,JJ,3,JJ NN VB,3,JJ NNP VB,0,rural,71,1.435215,101.900292,0.369792,1.435215,0.530731
hand,348,4,0.000081,13.591720,NN,NN,1,NN,2,NN NNP,0,hand,71,1.435215,101.900292,0.369792,1.435215,0.530731
servants,347,8,0.000081,13.595871,NNS,NN,2,NN VB,5,NN NNP NNS VBZ NNPS,0,servant,71,1.435215,101.900292,0.369792,1.435215,0.530731
like,303,4,0.000071,13.791489,JJ,JJ,3,JJ IN VB,3,JJ IN VB,0,like,71,1.435215,101.900292,0.369792,1.435215,0.530731
organized,299,9,0.000070,13.810662,VBN,VB,3,JJ NN VB,4,JJ NNP VBN VBD,0,organ,71,1.435215,101.900292,0.369792,1.435215,0.530731
class,291,5,0.000068,13.849788,NN,NN,1,NN,2,NN NNP,0,class,71,1.435215,101.900292,0.369792,1.435215,0.530731
fees,251,4,0.000058,14.063120,NNS,NN,1,NN,1,NNS,0,fee,71,1.435215,101.900292,0.369792,1.435215,0.530731
magistrate,234,10,0.000054,14.164299,NN,NN,3,JJ NN VB,5,JJ NN NNP VB VBP,0,magistr,71,1.435215,101.900292,0.369792,1.435215,0.530731
delivered,221,9,0.000051,14.246761,VBN,VB,2,JJ VB,3,JJ VBN VBD,0,deliv,71,1.435215,101.900292,0.369792,1.435215,0.530731
occasion,221,8,0.000051,14.246761,NN,NN,1,NN,1,NN,0,occas,71,1.435215,101.900292,0.369792,1.435215,0.530731
reading,220,7,0.000051,14.253304,NN,NN,2,NN VB,3,NN NNP VBG,0,read,71,1.435215,101.900292,0.369792,1.435215,0.530731
construction,207,12,0.000048,14.341176,NN,NN,1,NN,2,NN NNP,0,construct,71,1.435215,101.900292,0.369792,1.435215,0.530731
copy,206,4,0.000048,14.348163,NN,NN,1,NN,2,NN NNP,0,copi,71,1.435215,101.900292,0.369792,1.435215,0.530731
read,202,4,0.000047,14.376452,VBN,VB,3,JJ NN VB,7,JJ NN NNP VB VBP VBN VBD,0,read,71,1.435215,101.900292,0.369792,1.435215,0.530731
integral,180,8,0.000042,14.542810,JJ,JJ,2,JJ NN,2,JJ NNP,0,integr,71,1.435215,101.900292,0.369792,1.435215,0.530731
honor,179,5,0.000042,14.550848,NN,NN,4,JJ NN VB PD,7,JJ NN NNP VB NNS VBP PDT,0,honor,71,1.435215,101.900292,0.369792,1.435215,0.530731
requirement,169,11,0.000039,14.633784,NN,NN,1,NN,1,NN,0,requir,71,1.435215,101.900292,0.369792,1.435215,0.530731
regardless,144,10,0.000034,14.864738,NN,NN,4,JJ NN VB RB,5,JJ NN NNP VB RB,0,regardless,71,1.435215,101.900292,0.369792,1.435215,0.530731

In [29]:
# Check LIB Strucutre
LIB.head(20)

,source_file_path,country,file_year,title,original_year,revision_year,provision_regex,constitution_len,n_provisions,n_chars
constitution_id,,,,,,,,,,
Afghanistan_2004,./data/Afghanistan_2004.txt,Afghanistan,2004,Afghanistan,2004.0,<NA>,(?:^Preamble$)|(?:^(?:PART|Part)\b)|(?:^(?:TIT...,10435,175,66806
Albania_2008,./data/Albania_2008.txt,Albania,2008,Albania,1998.0,2008,(?:^Preamble$)|(?:^(?:PART|Part)\b)|(?:^(?:TIT...,13896,623,86022
Algeria_2008,./data/Algeria_2008.txt,Algeria,2008,Algeria,1963.0,2008,(?:^Preamble$)|(?:^(?:PART|Part)\b)|(?:^(?:TIT...,10605,197,66590
Andorra_1993,./data/Andorra_1993.txt,Andorra,1993,Andorra,1993.0,<NA>,(?:^Preamble$)|(?:^(?:PART|Part)\b)|(?:^(?:TIT...,8722,295,55687
Angola_2010,./data/Angola_2010.txt,Angola,2010,Angola,2010.0,<NA>,(?:^Preamble$)|(?:^(?:PART|Part)\b)|(?:^(?:TIT...,26657,856,175148
Antigua_and_Barbuda_1981,./data/Antigua_and_Barbuda_1981.txt,Antigua and Barbuda,1981,Antigua and Barbuda,1981.0,<NA>,(?:^Preamble$)|(?:^(?:PART|Part)\b)|(?:^(?:TIT...,36749,605,214275
Argentina_1994,./data/Argentina_1994.txt,Argentina,1994,"Argentina 1853 (reinst. 1983, rev. 1994)",NaN,NaN,(?:^Preamble$)|(?:^(?:PART|Part)\b)|(?:^(?:TIT...,13093,170,82255
Armenia_2005,./data/Armenia_2005.txt,Armenia,2005,Armenia,1995.0,2005,(?:^Preamble$)|(?:^(?:PART|Part)\b)|(?:^(?:TIT...,13908,153,86487
Australia_1985,./data/Australia_1985.txt,Australia,1985,Australia,1901.0,1985,(?:^Preamble$)|(?:^(?:PART|Part)\b)|(?:^(?:TIT...,13491,174,81224
Austria_2009,./data/Austria_2009.txt,Austria,2009,"Austria 1920 (reinst. 1945, rev. 2009)",NaN,NaN,(?:^Preamble$)|(?:^(?:PART|Part)\b)|(?:^(?:TIT...,44524,707,275162
Azerbaijan_2009,./data/Azerbaijan_2009.txt,Azerbaijan,2009,Azerbaijan,1995.0,2009,(?:^Preamble$)|(?:^(?:PART|Part)\b)|(?:^(?:TIT...,17388,184,110090
Bahamas_2002,./data/Bahamas_2002.txt,Bahamas,2002,Bahamas,1973.0,2002,(?:^Preamble$)|(?:^(?:PART|Part)\b)|(?:^(?:TIT...,38956,635,227497
Bahrain_2002,./data/Bahrain_2002.txt,Bahrain,2002,Bahrain,2002.0,<NA>,(?:^Preamble$)|(?:^(?:PART|Part)\b)|(?:^(?:TIT...,10859,141,66490
Bangladesh_2011,./data/Bangladesh_2011.txt,Bangladesh,2011,"Bangladesh 1972 (reinst. 1986, rev. 2011)",NaN,NaN,(?:^Preamble$)|(?:^(?:PART|Part)\b)|(?:^(?:TIT...,26199,549,158974
Barbados_2007,./data/Barbados_2007.txt,Barbados,2007,Barbados,1966.0,2007,(?:^Preamble$)|(?:^(?:PART|Part)\b)|(?:^(?:TIT...,34291,495,199629
Belarus_2004,./data/Belarus_2004.txt,Belarus,2004,Belarus,1994.0,2004,(?:^Preamble$)|(?:^(?:PART|Part)\b)|(?:^(?:TIT...,13593,164,85386
Belgium_2012,./data/Belgium_2012.txt,Belgium,2012,Belgium,1831.0,2012,(?:^Preamble$)|(?:^(?:PART|Part)\b)|(?:^(?:TIT...,16746,301,103438
Belize_2001,./data/Belize_2001.txt,Belize,2001,Belize,1981.0,2001,(?:^Preamble$)|(?:^(?:PART|Part)\b)|(?:^(?:TIT...,40230,677,235373
Benin_1990,./data/Benin_1990.txt,Benin,1990,Benin,1990.0,<NA>,(?:^Preamble$)|(?:^(?:PART|Part)\b)|(?:^(?:TIT...,11382,173,70742
Bhutan_2008,./data/Bhutan_2008.txt,Bhutan,2008,Bhutan,2008.0,<NA>,(?:^Preamble$)|(?:^(?:PART|Part)\b)|(?:^(?:TIT...,13715,392,84780

In [35]:
# Print average characters per document
print(LIB['n_chars'].mean())

138099.45833333334

# Get rows and columns for each table

In [32]:
comparison = pd.DataFrame({
    "table": ["LIB", "CORPUS", "VOCAB"],
    "n_rows": [LIB.shape[0], CORPUS.shape[0], VOCAB.shape[0]],
    "n_cols": [LIB.shape[1], CORPUS.shape[1], VOCAB.shape[1]],
})
comparison

    table   n_rows  n_cols
0     LIB      192      10
1  CORPUS  4296300       4
2   VOCAB    24868      18

# Save csvs

In [31]:
save_path = f"{output_dir}/{data_prefix}"

Path(output_dir).mkdir(exist_ok=True)
LIB.to_csv(f"{save_path}-LIB.csv", sep=CSV_DELIM)
#PROVISIONS.to_csv(f"{save_path}-PROVISIONS.csv", sep=CSV_DELIM, index=False)
CORPUS.to_csv(f"{save_path}-CORPUS.csv", sep=CSV_DELIM)
VOCAB.to_csv(f"{save_path}-VOCAB.csv", sep=CSV_DELIM)
DOC.to_csv(f"{save_path}-DOC.csv", sep=CSV_DELIM)